### ISSUE TITLE
报解码错误是怎么回事？

### ISSUE THREAD

**Issue by baiyifengyun** [alipay/alipay-easysdk#110]
org.bouncycastle.util.encoders.DecoderException: unable to decode base64 data: invalid characters encountered in base64 data
	at org.bouncycastle.util.encoders.Base64.decode(Unknown Source) ~[alipay-easysdk-2.0.1.jar:na]
	at com.alipay.easysdk.kernel.util.Signer.sign(Signer.java:84) ~[alipay-easysdk-2.0.1.jar:na]
	at com.alipay.easysdk.kernel.Client.sign(Client.java:361) ~[alipay-easysdk-2.0.1.jar:na]
	at com.alipay.easysdk.payment.facetoface.Client.preCreate(Client.java:150) ~[alipay-easysdk-2.0.1.jar:na]
	at com.fengyun.medicallab.service.impl.MedicalLabServicePayImpl.alipayment(MedicalLabServicePayImpl.java:57) ~[classes/:na]
	at org.apache.dubbo.common.bytecode.Wrapper3.invokeMethod(Wrapper3.java) ~[dubbo-2.7.6.jar:na]
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:44) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:118) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:152) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:145) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) ~[dubbo-2.7.6.jar:2.7.6]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: java.io.IOException: invalid characters encountered in base64 data
	at org.bouncycastle.util.encoders.Base64Encoder.decode(Unknown Source) ~[alipay-easysdk-2.0.1.jar:na]
	... 34 common frames omitted

调用遭遇异常，原因：签名遭遇异常，content=alipay_sdk=alipay-easysdk-java-2.0.0&app_id=<-- 2016101900722131 -->&biz_content={"out_trade_no":"2234567890","total_amount":"5799.00","subject":"Apple iPhone11 128G"}&charset=UTF-8&format=json&method=alipay.trade.precreate&sign_type=RSA2&timestamp=2020-08-02 01:57:18&version=1.0 privateKeySize=1628 reason=unable to decode base64 data: invalid characters encountered in base64 data

**Comment by antopen** [comment]
请检查应用私钥是否设置正确。
