### ISSUE TITLE
spring boot 2.3.2调用Factory.Payment.FaceToFace().preCreate异常，返回非json，看到有类似问题，但是未给出解决方案，请问如何解决？

### ISSUE THREAD

**Issue by zhaohr1107** [alipay/alipay-easysdk#123]
调用遭遇异常，原因：java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:46)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.alipay.easysdk.kernel.Client.readAsJson(Client.java:129)
	at com.alipay.easysdk.payment.facetoface.Client.preCreate(Client.java:159)
	at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:37)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 6 more

**Comment by zhaohr1107** [comment]
//沙箱环境   https://openapi.alipaydev.com/gateway.do
        config.protocol = "https";
        config.gatewayHost = "openapi.alipaydev.com/gateway.do";

**Comment by antopen** [comment]
config.gatewayHost = "openapi.alipaydev.com"，不能带/gateway.do后缀。

**Comment by zhaohr1107** [comment]
> config.gatewayHost =“ openapi.alipaydev.com”，不能带/gateway.do后缀。

感谢！
