### ISSUE TITLE
java.lang.NoSuchMethodError: okhttp3.Headers.iterator()Ljava/util/Iterator;

### ISSUE THREAD

**Issue by yuancihang** [alipay/alipay-easysdk#129]
java.lang.NoSuchMethodError: okhttp3.Headers.iterator()Ljava/util/Iterator;

	at com.aliyun.tea.TeaResponse.<init>(TeaResponse.java:30)
	at com.aliyun.tea.Tea.doAction(Tea.java:63)
	at com.alipay.easysdk.payment.common.Client.query(Client.java:154)
	at com.happyelements.hei.cases.ChannelNotifyCase.runAlipayQuery(ChannelNotifyCase.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

使用的maven依赖：

   <dependency>
	   <groupId>com.alipay.sdk</groupId>
	   <artifactId>alipay-easysdk</artifactId>
	   <version>2.0.2</version>
  </dependency>

**Comment by yuancihang** [comment]
升级到okhttp4.0以上解决
