### ISSUE TITLE
调用Factory.Payment.Common().query()失败

### ISSUE THREAD

**Issue by czlcccz** [alipay/alipay-easysdk#14]
```
java.lang.IllegalArgumentException: Can not set [Lcom.alipay.easysdk.payment.common.models.TradeFundBill; field com.alipay.easysdk.payment.common.models.AlipayTradeQueryResponse.fundBillList to java.util.ArrayList
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.aliyun.tea.TeaModel.toModel(TeaModel.java:95)
	at com.alipay.easysdk.payment.common.Client.query(Client.java:161)
```
在预下单成功后查询支付状态，这是预下单时请求的参数结构。
```JSON
{
  "out_trade_no":"xx",
  "total_amount":"xx",
  "subject":"xx",
  "goods_detail":[
     {
        "goods_id":"xx",
        "goods_name":"xx",
        "price":"xx",
        "quantity":xx
     }
   ]
}
```

**Comment by antopen** [comment]
感谢反馈，原因已经定位，我们今天会发布一版马上修复。

**Comment by antopen** [comment]
已在1.1.2版本中修复。
