### ISSUE TITLE
Factory.Payment.Common().query  java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by pangzixianrenzhang** [alipay/alipay-easysdk#151]
java.lang.NoClassDefFoundError: Could not initialize class okhttp3.OkHttpClient
at com.aliyun.tea.okhttp.OkHttpClientBuilder.<init>(OkHttpClientBuilder.java:25) ~[tea-1.0.3.jar!/:?]
        at com.aliyun.tea.okhttp.ClientHelper.creatClient(ClientHelper.java:32) ~[tea-1.0.3.jar!/:?]
        at com.aliyun.tea.okhttp.ClientHelper.getOkHttpClient(ClientHelper.java:25) ~[tea-1.0.3.jar!/:?]
        at com.aliyun.tea.Tea.doAction(Tea.java:58) ~[tea-1.0.3.jar!/:?]
        at com.alipay.easysdk.payment.common.Client.query(Client.java:154) ~[alipay-easysdk-2.0.2.jar!/:?]

**Comment by pangzixianrenzhang** [comment]
spring-boot +dubbo，手动增加okhttp 4.8.1 依赖,spring-core升级至5.0.9 仍然是这个错误

**Comment by pangzixianrenzhang** [comment]
补充说明下： 支付和回调都正常. Factory.Payment.Common().query()接口失败
 java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto

 加入okhttp 4.8.1版本，依然失败
java.lang.NoClassDefFoundError: Could not initialize class okhttp3.OkHttpClient
at com.aliyun.tea.okhttp.OkHttpClientBuilder.<init>(OkHttpClientBuilder.java:25) ~[tea-1.0.3.jar!/:?]

本地环境spring-boot 2.0.5 + dubbo  
更改easysdk 2.0.0 查询正常，官方莫不是发了个bug的版本吧

**Comment by liangxp** [comment]
我也遇到OKHTTP版本问题，还在折腾中！
