### ISSUE TITLE
Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by qqliuxiaoran** [alipay/alipay-easysdk#176]
public static void main(String[] args) throws Exception {
        // 1. 设置参数（全局只需设置一次）
        Factory.setOptions(getOptions());
        try {
            // 2. 发起API调用（以创建当面付收款二维码为例）
            AlipayTradePrecreateResponse response = Factory.Payment.FaceToFace()
                    .preCreate("Apple iPhone11 128G", "2234567890", "5799.00");
            // 3. 处理响应或异常
            if (ResponseChecker.success(response)) {
                System.out.println("调用成功");
                System.out.println(response.outTradeNo);
                System.out.println(response.qrCode);
            } else {
                System.err.println("调用失败，原因：" + response.msg + "，" + response.subMsg);
            }
        } catch (Exception e) {
            System.err.println("调用遭遇异常，原因：" + e.getMessage());
            throw new RuntimeException(e.getMessage(), e);
        }
    }

.preCreate中抛出异常
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)

**Comment by fl0w2o48** [comment]
我也是遇到了这个问题，你有解决嘛

**Comment by qqliuxiaoran** [comment]
> 我也是遇到了这个问题，你有解决嘛

我最后使用的旧版sdk，没问题。而且文档里很多用例都是旧版sdk。

**Comment by VVlhw** [comment]
config.gatewayHost = "openapi.alipaydev.com";
config.alipayPublicKey 是支付宝公钥、非应用公钥
