### ISSUE TITLE
A connection to https://openapi.alipay.com/ was leaked. Did you forget to close a response body

### ISSUE THREAD

**Issue by Blackdread** [alipay/alipay-easysdk#199]
Hi, get this warning all the time with latest version of sdk.

It is when I use method: `xxxxxx.Payment.common().query(outTradeNo)`

```
2020-12-30T02:50:14.183Z [warn] okhttp3.OkHttpClient - A connection to https://openapi.alipay.com/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:143)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:78)
	at okhttp3.RealCall.execute(RealCall.java:66)
	at com.aliyun.tea.Tea.doAction(Tea.java:66)
	at com.alipay.easysdk.payment.common.Client.query(Client.java:154)
	at com.xxxxxx.xxxxxx.alipay.impl.service.payment.PaymentOrderCheckService.$anonfun$queryAndUpdatePayment$4(PaymentOrderCheckService.scala:28)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:661)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by Blackdread** [comment]
@antopen ??
