### ISSUE TITLE
org.bouncycastle 1.64没有 Base64.toBase64String问题

### ISSUE THREAD

**Issue by lyh061619** [alipay/alipay-easysdk#214]
public static String getCertPublicKey(String certContent) {
        try {
            InputStream inputStream = new ByteArrayInputStream(certContent.getBytes());
            CertificateFactory factory = CertificateFactory.getInstance("X.509", "BC");
            X509Certificate cert = (X509Certificate) factory.generateCertificate(inputStream);
            return Base64.toBase64String(cert.getPublicKey().getEncoded());
        } catch (Exception e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }
    报这个错误：
    	at com.alipay.easysdk.kernel.util.AntCertificationUtil.getCertPublicKey(AntCertificationUtil.java:350)
	at com.alipay.easysdk.kernel.CertEnvironment.<init>(CertEnvironment.java:57)
	at com.alipay.easysdk.kernel.Context.<init>(Context.java:49)
	at com.alipay.easysdk.factory.Factory.setOptions(Factory.java:40)
	at 

建议要么换掉代码中的toBase64String,要么降到1.59版本。

**Comment by lyh061619** [comment]
重新导包了下又找到了，这个问题可能我本地maven库存在一个重影包，现在找到了。
