### ISSUE TITLE
C# .Net5版本调用支付出现异常： The given key 'sign' was not present in the dictionary.

### ISSUE THREAD

**Issue by Best-Maple** [alipay/alipay-easysdk#266]
工具：Vs2019
----------------------
环境：.Net5.0
----------------------
异常代码：
`using Alipay.EasySDK.Factory;
using Alipay.EasySDK.Kernel.Util;
using Alipay.EasySDK.Payment.FaceToFace.Models;
using Furion.DependencyInjection;
using SqlSugar;
using System;
using System.Threading.Tasks;
using XHService.Application.BaseRepository;

namespace XHService.Application.AliPayBusiness.AliPayService
{

    public class AliPayService : BaseSqlSugarRepository, IAliPayService, ITransient
    {
        public AliPayService(ISqlSugarRepository sqlSugarRepository)
            : base(sqlSugarRepository)
        {

        }

        public async Task<bool> Pay(string goodsName, string orderNo, string money)
        {
             **AlipayTradePrecreateResponse response = await Factory.Payment.FaceToFace()
                .PreCreateAsync(goodsName, orderNo, money);**
            if (ResponseChecker.Success(response))
            {
                Console.WriteLine("调用成功");
                return true;
            }
            else
            {
                Console.WriteLine("调用失败，原因：" + response.Msg + "，" + response.SubMsg);
                return false;
            }
        }
    }
}`
-------------------------
异常堆栈信息：
`   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at XHService.Application.AliPayBusiness.AliPayController.Pay(String name, String no, String money) in D:\Company Project\XHService - 副本\XHService\XHService.Application\AliPayBusiness\AliPayController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()`

**Comment by Best-Maple** [comment]
查看源码看到在Create发送后，拿到响应报文时，对内容做了Sing的校验
```
TeaResponse response_ = TeaCore.DoAction(request_, runtime_);

                    Dictionary<string, object> respMap = this._kernel.ReadAsJson(response_, "alipay.trade.create");
                    if (this._kernel.IsCertMode())
                    {
                        if (**this._kernel.Verify**(respMap, this._kernel.ExtractAlipayPublicKey(this._kernel.GetAlipayCertSN(respMap))))
                        {
                            return TeaModel.ToObject<AlipayTradeCreateResponse>(this._kernel.ToRespModel(respMap));
                        }
                    }
                    else
                    {
                        if (**this._kernel.Verify**(respMap, this._kernel.GetConfig("alipayPublicKey")))
                        {
                            return TeaModel.ToObject<AlipayTradeCreateResponse>(this._kernel.ToRespModel(respMap));
                        }
                    }
```
校验方法如下：
```
// Alipay.EasySDK.Kernel.Client
// Token: 0x0600001E RID: 30 RVA: 0x000026E8 File Offset: 0x000008E8
public bool Verify(Dictionary<string, object> respMap, string alipayPublicKey)
{
	string sign = (string)respMap["sign"];
	return Signer.Verify(SignContentExtractor.GetSignSourceData((string)respMap["http_body"], (string)respMap["method"]), sign, alipayPublicKey);
}
```
但是在调用接口失败时，部分情况下（我这里是用沙箱环境的appid调用时，网关填写的正式环境的网关地址），返回内容是没有sing这个消息的：
![image](https://user-images.githubusercontent.com/52701673/126861383-cb53806a-70a5-427d-82ab-08e7aeac7795.png)

这时候就报上述错误了。

这一点没考虑键是否存在的问题。。。。

**Comment by stevendone** [comment]
阿里的开源就这德行，开源完就没人管了
