### ISSUE TITLE
使用官方demo报错，javaweb项目，非maven

### ISSUE THREAD

**Issue by fengmingmin** [alipay/alipay-easysdk#59]
使用官方demo报错，javaweb项目，非maven。打包后的jar包中根本就没有BaseClient$Config，下载到的项目源码也没有这个class。运行的时候在
Config config = new Config();这个位置报错，看到网上的例子使用BaseClient.Config config = new BaseClient.Config();也是同样报错。

下面是错误日志：
java.lang.ClassNotFoundException: com.alipay.easysdk.kernel.BaseClient$Config
 at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1328)
 at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1156)
 at service.PayService.getOptions(PayService.java:32)
 at service.PayService.aLiZhifu(PayService.java:59)
 at service.PayService.getPayStr(PayService.java:25)

**Comment by antopen** [comment]
最新2.0版本中的Config的包路径已更改为
import com.alipay.easysdk.kernel.Config;
