### ISSUE TITLE
使用SpringBoot2.3.1 调用SDK报错,提示GSON问题

### ISSUE THREAD

**Issue by zangxiyang** [alipay/alipay-easysdk#77]
```java
AlipayTradePrecreateResponse response = Factory.Payment
                    .FaceToFace()
                    .preCreate("test","123456789","6000.00");
```
在这一串代码的` .preCreate("test","123456789","6000.00");`这一行报错。

以下是错误信息，使用的是沙箱环境
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386) ~[alipay-easysdk-2.0.0.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[alipay-easysdk-2.0.0.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[alipay-easysdk-2.0.0.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[alipay-easysdk-2.0.0.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[alipay-easysdk-2.0.0.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[alipay-easysdk-2.0.0.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[alipay-easysdk-2.0.0.jar:na]
	at com.alipay.easysdk.kernel.Client.readAsJson(Client.java:129) ~[alipay-easysdk-2.0.0.jar:na]
	at com.alipay.easysdk.payment.facetoface.Client.preCreate(Client.java:159) ~[alipay-easysdk-2.0.0.jar:na]
	at com.imsle.heartpay.controller.PayController.test(PayController.java:38) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```

**Comment by antopen** [comment]
这通常是由于网关返回的字符串不是一个JSON，有可能是网关地址设置不对，或者沙箱当时正在维护等各类原因所致。
建议进钉钉交流群中提供更多信息进行定位。

**Comment by zhaohr1107** [comment]
我使用沙箱环境也遇到了，返回不正确，请问最后怎么处理的？
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:40)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.alipay.easysdk.kernel.Client.readAsJson(Client.java:129)
	at com.alipay.easysdk.payment.facetoface.Client.preCreate(Client.java:159)
	at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:31)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 6 more

**Comment by zangxiyang** [comment]
> 我使用沙箱环境也遇到了，返回不正确，请问最后怎么处理的？
> Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:40)
> Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> at com.google.gson.Gson.fromJson(Gson.java:944)
> at com.google.gson.Gson.fromJson(Gson.java:897)
> at com.google.gson.Gson.fromJson(Gson.java:846)
> at com.google.gson.Gson.fromJson(Gson.java:817)
> at com.alipay.easysdk.kernel.Client.readAsJson(Client.java:129)
> at com.alipay.easysdk.payment.facetoface.Client.preCreate(Client.java:159)
> at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:31)
> Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
> at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
> at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
> at com.google.gson.Gson.fromJson(Gson.java:932)
> ... 6 more

检查沙箱环境的地址是否正确

**Comment by zhaohr1107** [comment]
//https://openapi.alipaydev.com/gateway.do
config.protocol = "https";
config.gatewayHost = "openapi.alipaydev.com/gateway.do";
请问这样写的话，有什么问题吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alipay/alipay-easysdk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 下午4:09
收件人:&nbsp;"alipay/alipay-easysdk"<alipay-easysdk@noreply.github.com&gt;;
抄送:&nbsp;"z"<2900930@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alipay/alipay-easysdk] 使用SpringBoot2.3.1 调用SDK报错,提示GSON问题 (#77)





  
我使用沙箱环境也遇到了，返回不正确，请问最后怎么处理的？
 Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
 at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:40)
 Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
 at com.google.gson.Gson.fromJson(Gson.java:944)
 at com.google.gson.Gson.fromJson(Gson.java:897)
 at com.google.gson.Gson.fromJson(Gson.java:846)
 at com.google.gson.Gson.fromJson(Gson.java:817)
 at com.alipay.easysdk.kernel.Client.readAsJson(Client.java:129)
 at com.alipay.easysdk.payment.facetoface.Client.preCreate(Client.java:159)
 at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:31)
 Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
 at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
 at com.google.gson.Gson.fromJson(Gson.java:932)
 ... 6 more
  
检查沙箱环境的地址是否正确

**Comment by zhaohr1107** [comment]
//https://openapi.alipaydev.com/gateway.do
config.protocol = "https";
config.gatewayHost = "openapi.alipaydev.com/gateway.do";
请问这样写的话，有什么问题吗？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alipay/alipay-easysdk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 下午4:09
收件人:&nbsp;"alipay/alipay-easysdk"<alipay-easysdk@noreply.github.com&gt;;
抄送:&nbsp;"z"<2900930@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alipay/alipay-easysdk] 使用SpringBoot2.3.1 调用SDK报错,提示GSON问题 (#77)





  
我使用沙箱环境也遇到了，返回不正确，请问最后怎么处理的？
 Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
 at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:40)
 Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
 at com.google.gson.Gson.fromJson(Gson.java:944)
 at com.google.gson.Gson.fromJson(Gson.java:897)
 at com.google.gson.Gson.fromJson(Gson.java:846)
 at com.google.gson.Gson.fromJson(Gson.java:817)
 at com.alipay.easysdk.kernel.Client.readAsJson(Client.java:129)
 at com.alipay.easysdk.payment.facetoface.Client.preCreate(Client.java:159)
 at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:31)
 Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
 at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
 at com.google.gson.Gson.fromJson(Gson.java:932)
 ... 6 more
  
检查沙箱环境的地址是否正确

**Comment by zangxiyang** [comment]
> //https://openapi.alipaydev.com/gateway.do config.protocol = "https"; config.gatewayHost = "openapi.alipaydev.com/gateway.do"; 请问这样写的话，有什么问题吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alipay/alipay-easysdk" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 下午4:09 收件人:&nbsp;"alipay/alipay-easysdk"<alipay-easysdk@noreply.github.com&gt;; 抄送:&nbsp;"z"<2900930@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [alipay/alipay-easysdk] 使用SpringBoot2.3.1 调用SDK报错,提示GSON问题 (#77) 我使用沙箱环境也遇到了，返回不正确，请问最后怎么处理的？ Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:40) Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ at com.google.gson.Gson.fromJson(Gson.java:944) at com.google.gson.Gson.fromJson(Gson.java:897) at com.google.gson.Gson.fromJson(Gson.java:846) at com.google.gson.Gson.fromJson(Gson.java:817) at com.alipay.easysdk.kernel.Client.readAsJson(Client.java:129) at com.alipay.easysdk.payment.facetoface.Client.preCreate(Client.java:159) at cn.zhr.service.pay.ali.AliPayController.main(AliPayController.java:31) Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386) at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) at com.google.gson.Gson.fromJson(Gson.java:932) ... 6 more 检查沙箱环境的地址是否正确 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我之前出现问题之后用的原生的,没有使用easysdk包了,你的问题我也具体不是很清楚
