### ISSUE TITLE
包名和bcprov-jdk15on中的BouncyCastleProvider类包名完全一致，导致只会加载第一个

### ISSUE THREAD

**Issue by MyAuntIsPost90s** [alipay/alipay-easysdk#99]
报错如下：
java.lang.SecurityException: JCE cannot authenticate the provider BC
	at javax.crypto.Cipher.getInstance(Cipher.java:657) ~[?:1.8.0_122]
	at javax.crypto.Cipher.getInstance(Cipher.java:596) ~[?:1.8.0_122]
Caused by: java.util.jar.JarException: file:/C:/Users/11266/Documents/MyTool/gradle-4.8/crepository/caches/modules-2/files-2.1/com.alipay.sdk/alipay-easysdk/2.0.0/5aa27b9b874a5a5deed46c7638ab046ce29013c7/alipay-easysdk-2.0.0.jar has unsigned entries - com/alipay/easysdk/util/generic/models/AlipayOpenApiGenericResponse.class
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:502) ~[?:1.8.0_122]
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:363) ~[?:1.8.0_122]
	at javax.crypto.JarVerifier.verify(JarVerifier.java:289) ~[?:1.8.0_122]
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164) ~[?:1.8.0_122]
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190) ~[?:1.8.0_122]
	at javax.crypto.Cipher.getInstance(Cipher.java:653) ~[?:1.8.0_122]

我的代码：
`
Security.addProvider(new BouncyCastleProvider());
byte[] decodeData = Base64.getDecoder().decode(refundStr);
SecretKeySpec key = new SecretKeySpec(WxMd5Util.MD5Encode(mchKey, "utf-8").toLowerCase().getBytes(), "AES");
Cipher cipher = Cipher.getInstance("AES/ECB/PKCS7Padding", "BC");
`

**Comment by antopen** [comment]
感谢反馈，后续我们会跳转SDK的打包方式，让开发者可以灵活排除SDK中的依赖，使用项目本身已有的相同依赖。
